<?php

declare(strict_types=1);

// Register modules
// This file is auto-generated by make:module command
// You can manually add or remove modules from this array

return [
    // Core module must be loaded first as other modules depend on it
    App\Modules\Core\Infrastructure\Providers\CoreServiceProvider::class,

    // Auth module (handles both API and Web authentication)
    App\Modules\Auth\Infrastructure\Providers\AuthServiceProvider::class,

    // Feature modules
    App\Modules\User\Infrastructure\Providers\UserServiceProvider::class,
    App\Modules\Role\Infrastructure\Providers\RoleServiceProvider::class,
    App\Modules\Permission\Infrastructure\Providers\PermissionServiceProvider::class,

    // Add your module service providers here
    // Example: \App\Modules\Product\Infrastructure\Providers\ProductServiceProvider::class,
];
