#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Console\Commands\CreateControllerCommand;
use App\Console\Commands\ListRoutesCommand;
use App\Console\Commands\MakeModelCommand;
use App\Console\Commands\MakeRequestCommand;
use App\Console\Commands\SeedDatabaseCommand;
use Slim\Factory\AppFactory;
use Symfony\Component\Console\Application;

// Autoload dependencies
require __DIR__ . '/vendor/autoload.php';

// Create Slim app
$app = AppFactory::create();

// Load routes from routes/web.php
(require __DIR__ . '/routes/web.php')($app); // Execute the closure and pass the app
(require __DIR__ . '/routes/api.php')($app); // Execute the closure and pass the app
// Create console application
$application = new Application();

// Register the ListRoutesCommand and pass $app to it
$application->add(new ListRoutesCommand($app));
$application->add(new CreateControllerCommand);
$application->add(new MakeModelCommand());
$application->add(new MakeRequestCommand());
$application->add(new SeedDatabaseCommand());


// Run the console application
$application->run();
