#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Console\Commands\CreateControllerCommand;
use App\Console\Commands\ListRoutesCommand;
use App\Console\Commands\MakeModelCommand;
use App\Console\Commands\MakeModuleCommand;
use App\Console\Commands\MakeRequestCommand;
use App\Console\Commands\QueueFailedCommand;
use App\Console\Commands\QueueFlushCommand;
use App\Console\Commands\QueueRetryCommand;
use App\Console\Commands\QueueStatsCommand;
use App\Console\Commands\QueueWorkCommand;
use App\Console\Commands\SeedDatabaseCommand;
use DI\ContainerBuilder;
use Slim\Factory\AppFactory;
use Symfony\Component\Console\Application;

// Autoload dependencies
require __DIR__ . '/vendor/autoload.php';

// Initialize container for console commands
$containerBuilder = new ContainerBuilder();
$containerBuilder->useAutowiring(true);
$containerBuilder->addDefinitions(require __DIR__ . '/bootstrap/dependencies.php');
$container = $containerBuilder->build();

// Load database for queue commands (only if .env exists)
if (file_exists(__DIR__ . '/.env')) {
    require __DIR__ . '/bootstrap/database.php';
}

// Create Slim app
$app = AppFactory::create();

// Load routes from routes/web.php
(require __DIR__ . '/routes/web.php')($app); // Execute the closure and pass the app
(require __DIR__ . '/routes/api.php')($app); // Execute the closure and pass the app
// Create console application
$application = new Application();

// Register the ListRoutesCommand and pass $app to it
$application->add(new ListRoutesCommand($app));
$application->add(new CreateControllerCommand);
$application->add(new MakeModelCommand());
$application->add(new MakeModuleCommand());
$application->add(new MakeRequestCommand());
$application->add(new QueueWorkCommand($container->get(\App\Modules\Core\Infrastructure\Queue\Queue::class), $container));
$application->add(new QueueStatsCommand($container->get(\App\Modules\Core\Infrastructure\Queue\QueueManager::class)));
$application->add(new QueueFailedCommand());
$application->add(new QueueRetryCommand($container->get(\App\Modules\Core\Infrastructure\Queue\QueueManager::class)));
$application->add(new QueueFlushCommand());
$application->add(new SeedDatabaseCommand());


// Run the console application
$application->run();
