<?php

declare(strict_types=1);

namespace Tests\Unit\Console;

use App\Console\Commands\MakeModuleCommand;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

/**
 * make:module writes into the real project tree, so every bootstrap file it edits is
 * snapshotted here and restored byte-for-byte afterwards. Regex-based cleanup used to
 * leave `];` glued to the previous entry, which the next run then appended to —
 * corrupting bootstrap/dependencies.php a little more on every test run.
 */
final class MakeModuleCommandTest extends TestCase
{
    /**
     * Project files make:module is allowed to touch, relative to the project root.
     */
    private const array MUTABLE_FILES = [
        'bootstrap/dependencies.php',
        'bootstrap/modules-register.php',
    ];

    /**
     * Module directories generated by these tests, relative to the project root.
     */
    private const array GENERATED_MODULES = [
        'app/Modules/TestModule',
        'app/Modules/Product',
    ];

    private string $projectRoot;

    private string $testModulePath;

    /** @var array<string, string|null> absolute path => original contents (null when absent) */
    private array $snapshots = [];

    protected function setUp(): void
    {
        parent::setUp();
        // Get project root (3 levels up from tests/Unit/Console)
        $this->projectRoot = dirname(__DIR__, 3);
        $this->testModulePath = $this->projectRoot.'/app/Modules/TestModule';

        foreach (self::MUTABLE_FILES as $relative) {
            $path = $this->projectRoot.'/'.$relative;
            $this->snapshots[$path] = file_exists($path) ? (string) file_get_contents($path) : null;
        }
    }

    protected function tearDown(): void
    {
        foreach (self::GENERATED_MODULES as $relative) {
            $this->removeDirectory($this->projectRoot.'/'.$relative);
        }

        foreach ($this->snapshots as $path => $original) {
            if ($original === null) {
                if (file_exists($path)) {
                    unlink($path);
                }

                continue;
            }

            file_put_contents($path, $original);
        }

        $this->snapshots = [];

        parent::tearDown();
    }

    public function test_generated_dependencies_file_stays_valid_php(): void
    {
        $this->runMakeModule(['name' => 'TestModule']);

        $depsFile = $this->projectRoot.'/bootstrap/dependencies.php';

        $this->assertSame(
            0,
            $this->lint($depsFile),
            'make:module must leave bootstrap/dependencies.php syntactically valid.'
        );
    }

    public function test_generated_entries_do_not_glue_onto_the_closing_bracket(): void
    {
        $this->runMakeModule(['name' => 'TestModule']);

        $content = (string) file_get_contents($this->projectRoot.'/bootstrap/dependencies.php');

        $this->assertMatchesRegularExpression(
            '/,\s*\n\];/',
            $content,
            'The array closing bracket must keep its own line.'
        );
        $this->assertDoesNotMatchRegularExpression(
            '/\)\s{2,}\w+ActionInterface::class/',
            $content,
            'A generated entry must not share a line with the preceding entry.'
        );
    }

    public function test_repeated_runs_do_not_accumulate_duplicate_entries(): void
    {
        $this->runMakeModule(['name' => 'TestModule']);
        $this->removeDirectory($this->testModulePath);
        $this->runMakeModule(['name' => 'TestModule']);

        $content = (string) file_get_contents($this->projectRoot.'/bootstrap/dependencies.php');

        $this->assertSame(
            1,
            substr_count($content, 'CreateTestModuleActionInterface::class =>'),
            'An interface already present must not be registered twice.'
        );
    }

    public function test_make_module_creates_directory_structure(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        $this->assertDirectoryExists($this->testModulePath.'/Application/Actions');
        $this->assertDirectoryExists($this->testModulePath.'/Application/DTOs');
        $this->assertDirectoryExists($this->testModulePath.'/Infrastructure/Models');
        $this->assertDirectoryExists($this->testModulePath.'/Infrastructure/Repositories');
        $this->assertDirectoryExists($this->testModulePath.'/Infrastructure/Http/Controllers');
        $this->assertDirectoryExists($this->testModulePath.'/Infrastructure/Routes');
        $this->assertDirectoryExists($this->testModulePath.'/Policies');
    }

    public function test_make_module_creates_all_required_files(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        // Check Application layer files
        $this->assertFileExists($this->testModulePath.'/Application/Actions/CreateTestModuleAction.php');
        $this->assertFileExists($this->testModulePath.'/Application/Actions/UpdateTestModuleAction.php');
        $this->assertFileExists($this->testModulePath.'/Application/Actions/DeleteTestModuleAction.php');
        $this->assertFileExists($this->testModulePath.'/Application/Actions/GetTestModuleAction.php');
        $this->assertFileExists($this->testModulePath.'/Application/Actions/ListTestModuleAction.php');
        $this->assertFileExists($this->testModulePath.'/Application/DTOs/CreateTestModuleDTO.php');
        $this->assertFileExists($this->testModulePath.'/Application/DTOs/UpdateTestModuleDTO.php');

        // Check Infrastructure layer files
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Models/TestModule.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Repositories/TestModuleRepository.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Http/Controllers/TestModuleController.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Http/Requests/CreateTestModuleRequest.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Http/Requests/UpdateTestModuleRequest.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Http/Resources/TestModuleResource.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Providers/TestModuleServiceProvider.php');
        $this->assertFileExists($this->testModulePath.'/Infrastructure/Routes/api.php');
        $this->assertFileExists($this->testModulePath.'/Policies/TestModulePolicy.php');
    }

    public function test_make_module_registers_service_provider(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        $registerFile = $this->projectRoot.'/bootstrap/modules-register.php';
        $this->assertFileExists($registerFile);

        $content = file_get_contents($registerFile);
        $this->assertStringContainsString('App\\Modules\\TestModule\\Infrastructure\\Providers\\TestModuleServiceProvider', (string) $content);
    }

    public function test_make_module_with_custom_model_name(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute([
            'name' => 'Product',
            '--model' => 'Item',
        ]);

        $modulePath = $this->projectRoot.'/app/Modules/Product';
        $this->assertFileExists($modulePath.'/Infrastructure/Models/Item.php');
        $this->assertFileExists($modulePath.'/Infrastructure/Repositories/ItemRepository.php');
        $this->assertFileExists($modulePath.'/Application/Actions/CreateItemAction.php');
    }

    public function test_make_module_fails_if_module_exists(): void
    {
        // Create module first
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        // Try to create again
        $commandTester->execute(['name' => 'TestModule']);

        $this->assertSame(1, $commandTester->getStatusCode());
        $this->assertStringContainsString('already exists', $commandTester->getDisplay());
    }

    public function test_make_module_creates_interface_files(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        // Check Interface files
        $this->assertFileExists($this->testModulePath.'/Application/Interfaces/CreateTestModuleActionInterface.php');
        $this->assertFileExists($this->testModulePath.'/Application/Interfaces/UpdateTestModuleActionInterface.php');

        // Check that interfaces contain correct namespace
        $createInterfaceContent = file_get_contents($this->testModulePath.'/Application/Interfaces/CreateTestModuleActionInterface.php');
        $this->assertStringContainsString('namespace App\\Modules\\TestModule\\Application\\Interfaces', (string) $createInterfaceContent);
        $this->assertStringContainsString('interface CreateTestModuleActionInterface', (string) $createInterfaceContent);

        $updateInterfaceContent = file_get_contents($this->testModulePath.'/Application/Interfaces/UpdateTestModuleActionInterface.php');
        $this->assertStringContainsString('namespace App\\Modules\\TestModule\\Application\\Interfaces', (string) $updateInterfaceContent);
        $this->assertStringContainsString('interface UpdateTestModuleActionInterface', (string) $updateInterfaceContent);
    }

    public function test_make_module_actions_implement_interfaces(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        // Check that CreateAction implements interface
        $createActionContent = file_get_contents($this->testModulePath.'/Application/Actions/CreateTestModuleAction.php');
        $this->assertStringContainsString('implements CreateTestModuleActionInterface', (string) $createActionContent);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Interfaces\\CreateTestModuleActionInterface', (string) $createActionContent);

        // Check that UpdateAction implements interface
        $updateActionContent = file_get_contents($this->testModulePath.'/Application/Actions/UpdateTestModuleAction.php');
        $this->assertStringContainsString('implements UpdateTestModuleActionInterface', (string) $updateActionContent);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Interfaces\\UpdateTestModuleActionInterface', (string) $updateActionContent);
    }

    public function test_make_module_registers_action_interfaces_in_dependencies(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        $depsFile = $this->projectRoot.'/bootstrap/dependencies.php';
        $this->assertFileExists($depsFile);

        $content = file_get_contents($depsFile);

        // Check use statements
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Interfaces\\CreateTestModuleActionInterface', (string) $content);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Interfaces\\UpdateTestModuleActionInterface', (string) $content);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Actions\\CreateTestModuleAction', (string) $content);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Application\\Actions\\UpdateTestModuleAction', (string) $content);

        // Check registration in return array
        $this->assertStringContainsString('CreateTestModuleActionInterface::class', (string) $content);
        $this->assertStringContainsString('UpdateTestModuleActionInterface::class', (string) $content);
        $this->assertStringContainsString('\\DI\\autowire(CreateTestModuleAction::class)', (string) $content);
        $this->assertStringContainsString('\\DI\\autowire(UpdateTestModuleAction::class)', (string) $content);
    }

    public function test_make_module_service_provider_registers_repository(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute(['name' => 'TestModule']);

        $serviceProviderPath = $this->testModulePath.'/Infrastructure/Providers/TestModuleServiceProvider.php';
        $this->assertFileExists($serviceProviderPath);

        $content = file_get_contents($serviceProviderPath);

        // Check that Service Provider registers Repository
        $this->assertStringContainsString('TestModuleRepository::class', (string) $content);
        $this->assertStringContainsString('\\DI\\autowire(TestModuleRepository::class)', (string) $content);
        $this->assertStringContainsString('use App\\Modules\\TestModule\\Infrastructure\\Repositories\\TestModuleRepository', (string) $content);
    }

    public function test_make_module_with_custom_model_registers_correct_interfaces(): void
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $command = $application->find('make:module');
        $commandTester = new CommandTester($command);

        $commandTester->execute([
            'name' => 'Product',
            '--model' => 'Item',
        ]);

        $modulePath = $this->projectRoot.'/app/Modules/Product';
        $depsFile = $this->projectRoot.'/bootstrap/dependencies.php';

        // Check that correct interfaces are registered
        $content = file_get_contents($depsFile);
        $this->assertStringContainsString('CreateItemActionInterface', (string) $content);
        $this->assertStringContainsString('UpdateItemActionInterface', (string) $content);
        $this->assertStringContainsString('CreateItemAction', (string) $content);
        $this->assertStringContainsString('UpdateItemAction', (string) $content);
        $this->assertDirectoryExists($modulePath);
    }

    /**
     * @param  array<string, string>  $input
     */
    private function runMakeModule(array $input): CommandTester
    {
        $application = new Application();
        $application->add(new MakeModuleCommand());

        $commandTester = new CommandTester($application->find('make:module'));
        $commandTester->execute($input);

        return $commandTester;
    }

    private function lint(string $file): int
    {
        exec(sprintf('%s -l %s 2>&1', escapeshellarg(PHP_BINARY), escapeshellarg($file)), $ignored, $exitCode);

        return $exitCode;
    }

    private function removeDirectory(string $dir): void
    {
        if (! is_dir($dir)) {
            return;
        }

        $files = array_diff(scandir($dir), ['.', '..']);
        foreach ($files as $file) {
            $path = sprintf('%s/%s', $dir, $file);
            is_dir($path) ? $this->removeDirectory($path) : unlink($path);
        }

        rmdir($dir);
    }
}
