<?php

declare(strict_types=1);

namespace Tests\Integration;

use App\Modules\Core\Infrastructure\DI\OptimizedDiscovery;
use App\Modules\Core\Infrastructure\Support\AdvancedJwtServiceInterface;
use PHPUnit\Framework\TestCase;

/**
 * Integration tests for Auto-Discovery.
 *
 * Tests the discovery process with real file scanning.
 *
 * @covers \App\Modules\Core\Infrastructure\DI\OptimizedDiscovery
 */
final class AutoDiscoveryIntegrationTest extends TestCase
{
    private string $cacheFile;

    private string $cacheDir;

    private array $originalEnv;

    protected function setUp(): void
    {
        parent::setUp();
        $this->originalEnv = $_ENV;

        // A temporary cache path, so these tests never touch the project's own
        // storage/cache directory — one of them used to delete it outright.
        $this->cacheDir = sys_get_temp_dir().'/slim4mvc-discovery-'.bin2hex(random_bytes(6));
        $this->cacheFile = $this->cacheDir.'/autowiring.php';
    }

    protected function tearDown(): void
    {
        $_ENV = $this->originalEnv;

        if (file_exists($this->cacheFile)) {
            unlink($this->cacheFile);
        }

        if (is_dir($this->cacheDir)) {
            rmdir($this->cacheDir);
        }

        parent::tearDown();
    }

    public function test_it_scans_real_application_modules(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $definitions = $optimizedDiscovery->buildDefinitions();

        $this->assertIsArray($definitions);
        $this->assertNotEmpty($definitions);

        // Every key discovery produces must be a real interface — a stale cache or a
        // bad scan would surface here as a class name that no longer resolves.
        foreach (array_keys($definitions) as $interface) {
            $this->assertIsString($interface);
            $this->assertTrue(
                interface_exists((string) $interface),
                sprintf('Discovered "%s" is not an existing interface.', (string) $interface)
            );
        }

        $this->assertContains(AdvancedJwtServiceInterface::class, array_keys($definitions));
    }

    public function test_it_creates_readable_cache_file(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->buildDefinitions();

        $this->assertFileExists($this->cacheFile);

        $content = file_get_contents($this->cacheFile);
        $this->assertStringContainsString('<?php', (string) $content);
        $this->assertStringContainsString('Auto-generated by OptimizedDiscovery', (string) $content);
    }

    public function test_it_generates_valid_php_cache(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->buildDefinitions();

        // Cache should be valid PHP
        $definitions = require $this->cacheFile;
        $this->assertIsArray($definitions);
    }

    public function test_it_warms_cache_and_returns_stats(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);

        $this->assertFileDoesNotExist($this->cacheFile);

        $result = $optimizedDiscovery->warmCache();

        $this->assertFileExists($this->cacheFile);
        $this->assertArrayHasKey('count', $result);
        $this->assertArrayHasKey('duration', $result);
        $this->assertIsInt($result['count']);
        $this->assertIsFloat($result['duration']);
        $this->assertGreaterThanOrEqual(0, $result['duration']);
    }

    public function test_it_clears_cache_properly(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);

        // Create cache
        $optimizedDiscovery->warmCache();
        $this->assertFileExists($this->cacheFile);

        // Clear cache
        $result = $optimizedDiscovery->clearCache();

        $this->assertTrue($result);
        $this->assertFileDoesNotExist($this->cacheFile);
    }

    public function test_it_generates_statistics(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->warmCache();

        $stats = $optimizedDiscovery->getStats();

        $this->assertArrayHasKey('total_bindings', $stats);
        $this->assertArrayHasKey('cache_enabled', $stats);
        $this->assertArrayHasKey('cache_file', $stats);
        $this->assertArrayHasKey('cache_exists', $stats);
        $this->assertArrayHasKey('cache_valid', $stats);
        $this->assertArrayHasKey('environment', $stats);
        $this->assertArrayHasKey('sample_bindings', $stats);

        $this->assertIsInt($stats['total_bindings']);
        $this->assertIsBool($stats['cache_exists']);
        $this->assertTrue($stats['cache_exists']);
    }

    public function test_it_uses_cache_in_production(): void
    {
        $_ENV['APP_ENV'] = 'production';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->warmCache();

        $this->assertTrue($optimizedDiscovery->shouldUseCache());
    }

    public function test_it_respects_cache_ttl_in_development(): void
    {
        $_ENV['APP_ENV'] = 'local';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->warmCache();

        // Fresh cache should be valid
        $this->assertTrue($optimizedDiscovery->shouldUseCache());

        // Simulate old cache by modifying file time
        touch($this->cacheFile, time() - 7200); // 2 hours ago

        // Should not use expired cache in development
        $this->assertFalse($optimizedDiscovery->shouldUseCache());
    }

    public function test_it_returns_same_definitions_from_cache(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);

        // Get fresh definitions
        $fresh = $optimizedDiscovery->buildDefinitions();

        // Get cached definitions
        $cached = require $this->cacheFile;

        // Should have same keys
        $this->assertEquals(array_keys($fresh), array_keys($cached));
    }

    public function test_it_refreshes_cache_correctly(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);

        // Create initial cache
        $optimizedDiscovery->warmCache();

        $mtime1 = filemtime($this->cacheFile);

        // Wait a bit
        sleep(1);

        // Refresh cache
        $optimizedDiscovery->warmCache();
        $mtime2 = filemtime($this->cacheFile);

        // File should be newer
        $this->assertGreaterThan($mtime1, $mtime2);
    }

    public function test_it_handles_empty_scan_paths(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery([], $this->cacheFile);
        $definitions = $optimizedDiscovery->buildDefinitions();

        $this->assertIsArray($definitions);
        $this->assertEmpty($definitions);
    }

    public function test_it_handles_nonexistent_scan_paths(): void
    {
        $optimizedDiscovery = new OptimizedDiscovery(['/nonexistent/path'], $this->cacheFile);
        $definitions = $optimizedDiscovery->buildDefinitions();

        $this->assertIsArray($definitions);
        $this->assertEmpty($definitions);
    }

    public function test_it_creates_cache_directory_if_needed(): void
    {
        $this->assertDirectoryDoesNotExist($this->cacheDir);

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $optimizedDiscovery->warmCache();

        $this->assertDirectoryExists($this->cacheDir);
        $this->assertFileExists($this->cacheFile);
    }

    public function test_it_returns_correct_cache_file_path(): void
    {
        $path = OptimizedDiscovery::getCacheFile();

        $this->assertIsString($path);
        $this->assertStringContainsString('autowiring.php', $path);
        $this->assertStringContainsString('storage/cache', $path);
    }

    public function test_it_detects_staging_as_production(): void
    {
        $_ENV['APP_ENV'] = 'staging';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $stats = $optimizedDiscovery->getStats();

        $this->assertTrue($stats['cache_enabled']);
    }

    public function test_it_detects_local_as_development(): void
    {
        $_ENV['APP_ENV'] = 'local';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $stats = $optimizedDiscovery->getStats();

        $this->assertFalse($stats['cache_enabled']);
    }

    public function test_it_detects_development_as_development(): void
    {
        $_ENV['APP_ENV'] = 'development';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $stats = $optimizedDiscovery->getStats();

        $this->assertFalse($stats['cache_enabled']);
    }

    public function test_it_handles_unknown_environment(): void
    {
        $_ENV['APP_ENV'] = 'unknown';

        $optimizedDiscovery = new OptimizedDiscovery(cacheFile: $this->cacheFile);
        $stats = $optimizedDiscovery->getStats();

        $this->assertFalse($stats['cache_enabled']);
        $this->assertEquals('unknown', $stats['environment']);
    }
}
